### ISSUE TITLE
leaflet-locatecontrol - Release v0.45.1 - Icon / images NOT Showing in a Button

### ISSUE THREAD

**Issue by kipper65** [domoritz/leaflet-locatecontrol#145]
Hi,
In the demo >>> http://domoritz.github.io/leaflet-locatecontrol/demo/ are visible icons "locate.png" / "locate_active.png" / "spinner.gif" but when unloading "leaflet-locatecontrol- gh-pages.zip "icons are NOT present and the button is white. is a bug? Any suggestion for solve this problem?

Many Thanks

**Comment by domoritz** [comment]
This plugin does not use image icons any more. You can use font icons such as font awesome. See https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/demo/index.html#L7

**Comment by kipper65** [comment]
OK Dominik!

Many Thanks

Giuliano

Da: Dominik Moritz [mailto:notifications@github.com] 
Inviato: lunedì 30 novembre 2015 19:18
A: domoritz/leaflet-locatecontrol leaflet-locatecontrol@noreply.github.com
Cc: kipper65 giuliano@nespoli.eu
Oggetto: Re: [leaflet-locatecontrol] leaflet-locatecontrol - Release v0.45.1 - Icon / images NOT Showing in a Button (#145)

This plugin does not use image icons any more. You can use font icons such as font awesome. See https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/demo/index.html#L7

**Comment by h8nor** [comment]
If you do not want to connect a third-party font, you can add icons through your css:
``` css
.leaflet-control-locate a.leaflet-bar-part div {
	background-position: left 8px top 8px;
	background-repeat: no-repeat;
	width: 30px;
	height: 30px;
}
.leaflet-control-locate a.leaflet-bar-part div.loading {
	background-image: url(https://rawcdn.githack.com/gravitystorm/openstreetmap-carto/eae09090b64c361be3ff7bfd1975be7638a6b36c/symbols/man_made/tower_lattice_communication.svg);
}
.leaflet-control-locate a.leaflet-bar-part div.locate {
	background-image: url(https://rawcdn.githack.com/gravitystorm/openstreetmap-carto/eae09090b64c361be3ff7bfd1975be7638a6b36c/symbols/man_made/tower_lattice.svg);
}
```
Add the following code to the card:
``` js
const lc = L.control.locate({
	icon: 'locate',
	iconLoading: 'loading',
	iconElementTag: 'div'
}).addTo(map);
```
