### ISSUE TITLE
How do I make the locate button bigger?

### ISSUE THREAD

**Issue by radumas** [domoritz/leaflet-locatecontrol#164]
I'm trying to use this on mobile, and I find the locate icon to be a bit small. Is there a way to make the button + icon bigger through the options. Could this be added to the FAQ?

I've added the following to the `leaflet-bar-part` style but it's not centering well for some reason.

`"height: 1.5em; width: 1.5em;font-size: large;vertical-align: center; text-align: center"`

I also changed the icon to be crosshairs with `L.control.locate({icon: 'fa fa-crosshairs'})`

Result in Firefox on Ubuntu 

![selection_024](https://cloud.githubusercontent.com/assets/10623872/15190848/07830c4e-1780-11e6-8256-66173243713a.png)

**Comment by domoritz** [comment]
You'll have to change the CSS a bit more. You can use the style editor to change the CSS live in the browser. https://developer.mozilla.org/en-US/docs/Tools/Style_Editor

I'm closing this because it is not an issue with the control itself.

**Comment by kaio328** [comment]
I also got problem with styling the button... 

```
.leaflet-control-locate.active a {
}
```
and

```
.leaflet-control-locate.active.following a {
}
```
is simple. But i really struggle with
```
 .leaflet-control-locate a {
}
```

I  cant change anything : Color, border and even the size. Any hints?

**Comment by domoritz** [comment]
Can you make sure that you include your changes after the default css? I just tried this and it worked fine:

```css
.leaflet-control-locate a {
  width: 100px;
  height: 100px;
}
```

<img width="150" alt="screen shot 2017-02-07 at 12 25 45" src="https://cloud.githubusercontent.com/assets/589034/22709987/9251926a-ed30-11e6-9081-39b5e041cef7.png">

**Comment by kaio328** [comment]
I tried this:
```
.leaflet-control-locate a {
  font-size: 1.4em;
  color: #444;
  cursor: pointer;
  width: 100px;
  height: 100px;

}

.leaflet-control-locate.active a {
  color: #2074B6;
}
.leaflet-control-locate.active.following a {
  color: #FC8428;
}
```

Result: No changes. What am i doing wrong here?

Edit 1:
Very strange: I tried it with your example code. It works there! But if i try to implemant the same changes or even the same .css the behavior is totally diffrent. Im not able to change the border-radius for example.

Edit 2:
If i change the position to "topright" im able design the button. Not as easy as it is in your demo example but i managed somehow to add a border-radius and other stuff. If i then change the position back to "topright" the button looks totally different. Is there maybe any complication with other plugins? Im using leaflet-search and l.easy button aswell.

Edit 3:
Another question: if i remove every single code from the CSS the button changes his look to - i would call it - "default". How is that possible?

**Comment by domoritz** [comment]
Okay, I need more context. Can you give me a small html page with all your css?

I just tried 

```css
.leaflet-control-locate a {
  color: red;
  padding: 10px;
}

.leaflet-control-locate a span {
  font-size: 1.4em;
  cursor: pointer;
}

.leaflet-control-locate.active a {
  color: #2074B6;
}
.leaflet-control-locate.active.following a {
  color: #FC8428;
}
```

And get this

<img width="88" alt="screen shot 2017-02-08 at 10 53 13" src="https://cloud.githubusercontent.com/assets/589034/22752296/d0968078-edec-11e6-948e-a3cad1ace4d1.png">
