### ISSUE TITLE
Angular  ng build --prod  WARNING in Invalid property name 'r'

### ISSUE THREAD

**Issue by Toso82** [domoritz/leaflet-locatecontrol#252]
When i build my project:

```powershell
ng build --prod
```
```powershell
WARNING in Invalid property name 'r' at 5484:4. Ignoring.
```

I find that the problem it is in L.Control.Locate.css

```css
@keyframes leaflet-control-locate-throb {
  0% {
    r: 9;
    stroke-width: 1;
  }
  50% {
    r: 7;
    stroke-width: 3;
  }
  100% {
    r: 9;
    stroke-width: 1;
  }
}
```
As per the SVG 1.1 specification you can't style the r attribute of an SVG circle using CSS https://www.w3.org/TR/SVG/styling.html#SVGStylingProperties
